{
  rawRequest: IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    readable: false,
    _events: [Object: null prototype] {
      end: [Function: resetHeadersTimeoutOnReqEnd]
    },
    _eventsCount: 1,
    _maxListeners: undefined,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 8,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: true,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: [Server],
      _server: [Server],
      timeout: 120000,
      parser: [HTTPParser],
      on: [Function: socketListenerWrap],
      addListener: [Function: socketListenerWrap],
      prependListener: [Function: socketListenerWrap],
      _paused: false,
      _httpMessage: [ServerResponse],
      [Symbol(asyncId)]: 34,
      [Symbol(kHandle)]: [Pipe],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 120000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 815,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(asyncId)]: 35,
        [Symbol(triggerId)]: 34
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    connection: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 8,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: true,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: [Server],
      _server: [Server],
      timeout: 120000,
      parser: [HTTPParser],
      on: [Function: socketListenerWrap],
      addListener: [Function: socketListenerWrap],
      prependListener: [Function: socketListenerWrap],
      _paused: false,
      _httpMessage: [ServerResponse],
      [Symbol(asyncId)]: 34,
      [Symbol(kHandle)]: [Pipe],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 120000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 815,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(asyncId)]: 35,
        [Symbol(triggerId)]: 34
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    headers: {
      host: 'localhost:5001',
      connection: 'keep-alive',
      'content-length': '24',
      'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36',
      dnt: '1',
      'content-type': 'application/json',
      accept: '*/*',
      origin: 'http://localhost:8666',
      'sec-fetch-site': 'same-site',
      'sec-fetch-mode': 'cors',
      'sec-fetch-dest': 'empty',
      referer: 'http://localhost:8666/',
      'accept-encoding': 'gzip, deflate, br',
      'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
      authorization: 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjczNzVhZmY3MGRmZTNjMzNlOTBjYTM2OWUzYTBlZjQxMzE3MmZkODIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbHdkLWRiIiwiYXVkIjoibHdkLWRiIiwiYXV0aF90aW1lIjoxNjAwMzM0NzE1LCJ1c2VyX2lkIjoibjJjelNpQnBOM2JwS3pQeHhRdjN2WG90Tm43MiIsInN1YiI6Im4yY3pTaUJwTjNicEt6UHh4UXYzdlhvdE5uNzIiLCJpYXQiOjE2MDAzMzQ3MTUsImV4cCI6MTYwMDMzODMxNSwiZW1haWwiOiJzYXp6b3V6QG9wdGltaXR5LmNvLnVrIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInNhenpvdXpAb3B0aW1pdHkuY28udWsiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.CPxZyZYo7mFb1cIp6FHq-I_7Z2La6Aa0XlOPVcXfoUj7i-snQQ2MV-adMS7Ii0RQ0RLyr-L7hhrApN-UQtPGZiNqQVjzGkRo6kOsyxyFlTSkIeWCUT7rSLpgF9TM2jvxQw520HzFpYqR1O_f_D2blX5jLb6p2p_NFnsWYpOPNT10vsNKOuUKhrkW_FwVKkkEz6OHoxncv6TfZrFb934APnHArHbz5bB9fG_VVBswS1KPba5wtbsZYD-RxGHk1OO0EMKiWqxnQ7b433cVYzHv6buupYtA6xr17S6ZqHeYFGjK85x10EN4DjBNlXxGhbZwN9qPz6tTAxUq4MnZbF_2wA'
    },
    rawHeaders: [
      'host',
      'localhost:5001',
      'connection',
      'keep-alive',
      'content-length',
      '24',
      'user-agent',
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36',
      'dnt',
      '1',
      'content-type',
      'application/json',
      'accept',
      '*/*',
      'origin',
      'http://localhost:8666',
      'sec-fetch-site',
      'same-site',
      'sec-fetch-mode',
      'cors',
      'sec-fetch-dest',
      'empty',
      'referer',
      'http://localhost:8666/',
      'accept-encoding',
      'gzip, deflate, br',
      'accept-language',
      'en-GB,en-US;q=0.9,en;q=0.8',
      'x-original-auth',
      'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjczNzVhZmY3MGRmZTNjMzNlOTBjYTM2OWUzYTBlZjQxMzE3MmZkODIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbHdkLWRiIiwiYXVkIjoibHdkLWRiIiwiYXV0aF90aW1lIjoxNjAwMzM0NzE1LCJ1c2VyX2lkIjoibjJjelNpQnBOM2JwS3pQeHhRdjN2WG90Tm43MiIsInN1YiI6Im4yY3pTaUJwTjNicEt6UHh4UXYzdlhvdE5uNzIiLCJpYXQiOjE2MDAzMzQ3MTUsImV4cCI6MTYwMDMzODMxNSwiZW1haWwiOiJzYXp6b3V6QG9wdGltaXR5LmNvLnVrIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInNhenpvdXpAb3B0aW1pdHkuY28udWsiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.CPxZyZYo7mFb1cIp6FHq-I_7Z2La6Aa0XlOPVcXfoUj7i-snQQ2MV-adMS7Ii0RQ0RLyr-L7hhrApN-UQtPGZiNqQVjzGkRo6kOsyxyFlTSkIeWCUT7rSLpgF9TM2jvxQw520HzFpYqR1O_f_D2blX5jLb6p2p_NFnsWYpOPNT10vsNKOuUKhrkW_FwVKkkEz6OHoxncv6TfZrFb934APnHArHbz5bB9fG_VVBswS1KPba5wtbsZYD-RxGHk1OO0EMKiWqxnQ7b433cVYzHv6buupYtA6xr17S6ZqHeYFGjK85x10EN4DjBNlXxGhbZwN9qPz6tTAxUq4MnZbF_2wA',
      'x-callable-context-auth',
      '%7B%22uid%22%3A%22n2czSiBpN3bpKzPxxQv3vXotNn72%22%2C%22token%22%3A%7B%22iss%22%3A%22https%3A%2F%2Fsecuretoken.google.com%2Flwd-db%22%2C%22aud%22%3A%22lwd-db%22%2C%22auth_time%22%3A1600334715%2C%22user_id%22%3A%22n2czSiBpN3bpKzPxxQv3vXotNn72%22%2C%22sub%22%3A%22n2czSiBpN3bpKzPxxQv3vXotNn72%22%2C%22iat%22%3A1600334715%2C%22exp%22%3A1600338315%2C%22email%22%3A%22sazzouz%40optimity.co.uk%22%2C%22email_verified%22%3Afalse%2C%22firebase%22%3A%7B%22identities%22%3A%7B%22email%22%3A%5B%22sazzouz%40optimity.co.uk%22%5D%7D%2C%22sign_in_provider%22%3A%22password%22%7D%2C%22uid%22%3A%22n2czSiBpN3bpKzPxxQv3vXotNn72%22%7D%7D'
    ],
    trailers: {},
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '/',
    method: 'POST',
    statusCode: null,
    statusMessage: null,
    client: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 8,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: true,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: [Server],
      _server: [Server],
      timeout: 120000,
      parser: [HTTPParser],
      on: [Function: socketListenerWrap],
      addListener: [Function: socketListenerWrap],
      prependListener: [Function: socketListenerWrap],
      _paused: false,
      _httpMessage: [ServerResponse],
      [Symbol(asyncId)]: 34,
      [Symbol(kHandle)]: [Pipe],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 120000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 815,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(asyncId)]: 35,
        [Symbol(triggerId)]: 34
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _consuming: true,
    _dumped: false,
    next: [Function: next],
    baseUrl: '/lwd-db/europe-west2/authedFunction',
    originalUrl: '/lwd-db/europe-west2/authedFunction',
    _parsedUrl: Url {
      protocol: null,
      slashes: null,
      auth: null,
      host: null,
      port: null,
      hostname: null,
      hash: null,
      search: null,
      query: null,
      pathname: '/',
      path: '/',
      href: '/',
      _raw: '/'
    },
    params: { '0': '/' },
    query: {},
    res: ServerResponse {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: true,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: false,
      socket: [Socket],
      connection: [Socket],
      _header: null,
      _onPendingData: [Function: bound updateOutgoingData],
      _sent100: false,
      _expect_continue: false,
      req: [Circular],
      locals: [Object: null prototype] {},
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    body: { data: [Object] },
    _body: true,
    length: undefined,
    rawBody: <Buffer 7b 22 64 61 74 61 22 3a 7b 22 74 65 78 74 22 3a 22 71 77 64 71 22 7d 7d>,
    route: Route { path: '*', stack: [Array], methods: [Object] },
    [Symbol(kCapture)]: false
  },
  auth: {
    uid: 'n2czSiBpN3bpKzPxxQv3vXotNn72',
    token: {
      iss: 'https://securetoken.google.com/lwd-db',
      aud: 'lwd-db',
      auth_time: 1600334715,
      user_id: 'n2czSiBpN3bpKzPxxQv3vXotNn72',
      sub: 'n2czSiBpN3bpKzPxxQv3vXotNn72',
      iat: 1600334715,
      exp: 1600338315,
      email: 'sazzouz@optimity.co.uk',
      email_verified: false,
      firebase: [Object],
      uid: 'n2czSiBpN3bpKzPxxQv3vXotNn72'
    }
  }
}